# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_velocities:
      type: velocity_controllers/JointGroupVelocityController


    forward_position_controller:
      type: position_controllers/JointGroupPositionController


    open_manipulator_x_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - gripper
      - gripper_sub
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
joint_velocities:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - gripper
      - gripper_sub
forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - gripper
      - gripper_sub
open_manipulator_x_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity