controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_velocities:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - gripper
      - gripper_sub
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      joint1: { trajectory: 0.2, goal: 0.1 }
      joint2: { trajectory: 0.2, goal: 0.1 }
      joint3: { trajectory: 0.2, goal: 0.1 }
      joint4: { trajectory: 0.2, goal: 0.1 }
      gripper: { trajectory: 0.2, goal: 0.1 }
      gripper_sub: { trajectory: 0.2, goal: 0.1 }


joint_velocities:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - gripper
      - gripper_sub
    interface_name: velocity

forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - gripper
      - gripper_sub
